---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simetrikgrpc-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simetrikgrpc-pod
  template:
    metadata:
      labels:
        app: simetrikgrpc-pod
    spec:
      containers:
      - name: simetrikgrpc-container
        image: $$$$$$$$$$$$.dkr.ecr.us-east-2.amazonaws.com/simetrikgrpcrepo:1.1.0
        ports:
        - containerPort: 50051
        env:
        - name: RUNNER
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: simetrikgrpc-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  selector:
    app: simetrikgrpc-pod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simetrik-ab
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol-version: "GRPC"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  tls:
  - hosts:
    - insert.hostname.here
    secretName: sslCert
  ingressClassName: alb
  rules:
    - host: insert.hostname.here
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: simetrikgrpc-service
                port:
                  number: 50051